### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by rsv-code** [matjaz99/simple-logger#1]
Cool little logging library! I have a use for this, but there's no license applied, so I can't use it yet. Need to know the terms of use of the software.

**Comment by matjaz99** [comment]
Hello. I am glad you find this library useful. I added MIT License, as it is the most permissive one. I hope it suits your needs.
Regards, Matjaž

**Comment by rsv-code** [comment]
Hi Matjaž,
Thanks so much, that's perfect! I'm using your logger in a piece of software where I need many individual loggers each logging to different files. Your library is a perfect fit. Much appreciated!
Best, Austin
